config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'categories#index'
  resources :users, only: %i[new create]
  resources :articles, only: %i[new create show] do
    resources :comments
  end
  resources :categories, only: %i[new create show index]
  get '/vote/:article_id' => 'votes#add_vote', as: :add_vote

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :votes, foreign_key: :article_id
  has_many :voters, through: :votes, source: :user
  has_many :organizations, foreign_key: :article_id, inverse_of: :article
  has_many :categories, through: :organizations
  has_many :comments

  validates_presence_of :title
  validates_length_of :title, minimum: 4
  validates_presence_of :text
  validates_length_of :title, minimum: 4
  validates_presence_of :image
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :organizations, foreign_key: :category_id
  has_many :articles, -> { order(id: 'desc') }, through: :organizations
  validates_presence_of :name
  validates_length_of :name, minimum: 3
  validates_presence_of :priority
  validates :priority, uniqueness: true
  validates :name, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
  validates_presence_of :body
  validates_length_of :body, minimum: 1
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :category
  belongs_to :article
  accepts_nested_attributes_for :category

  validates_presence_of :category
  validates_presence_of :article
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, foreign_key: :author_id, class_name: 'Article'
  has_many :votes, foreign_key: :user_id
  has_many :voted_articles, through: :votes, source: :article
  has_many :comments
  validates_presence_of :name
  validates_length_of :name, minimum: 4
  validates :name, uniqueness: true
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user, class_name: 'User'
  belongs_to :article, class_name: 'Article'
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authorize, only: %i[index show new create]

  def index; end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      flash.notice = 'Article created!'
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @article = Article.includes(:comments, :author).find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :image, category_ids: [])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authorize, only: %i[index]

  def index
    @categories = Category.order('priority ASC').includes(:articles).select do |e|
      e.articles.count.positive?
    end
    if Vote.count.positive?
      @vote = Vote.all.group(:article_id).count.max_by { |_k, v| v }.first
      @article = Article.find(@vote)
    elsif Article.count.positive?
      @article = Article.first
    else
      redirect_to new_category_path
    end
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash.notice = 'Category created!'
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @category = Category.includes(articles: :author).find(params[:id])
  end

  private

  def category_params
    params.require(:category).permit(:name, :priority)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authorize, only: %i[create]

  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    @comment.user_id = current_user.id

    @comment.save
    flash.notice = 'Your comment has been added'
    redirect_to article_path(@comment.article)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by_name(params[:name])
    # If the user exists
    if @user
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = @user.id
      redirect_to root_path
    else
      # If user's login doesn't work, send them back to the login form.
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authorize, only: %i[add_vote]

  def add_vote
    @article = Article.find(params[:article_id])
    current_user.votes.create(article: @article)
    flash.notice = 'Vote added!'
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def handle_vote(article)
    if voted?(article)
      content_tag(:p, 'You have already voted this article', class: 'font-weight-bold mt-3')
    else
      link_to 'Vote', add_vote_path(article_id: article.id),
              class: 'text-center w-25 mt-3 mb-3 p-2 bg-acumin-color text-white rounded nav-link m-auto'
    end
  end

  def show_votes?(article)
    return unless article.votes.count.positive?

    content_tag(:p, "#{article.votes.count} vote(s)",
                class: 'w-50 m-auto font-weight-bold mt-3 alert alert-success rounded p-1')
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LifestyleApp</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://use.typekit.net/coi1grn.css" %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" %>
    <%=javascript_include_tag "https://kit.fontawesome.com/d86848cfe0.js"  %>

    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>

  <body class="">
    <header>
      <!-- desktop nav -->
      <nav class="navbar navbar-expand-sm bg-white border-bottom fixed-top first-nav">
        <ul class="navbar-nav flex-row align-items-center navbar-desktop">
          <li class="nav-item ml-3">
            <h3 class="font-weight-bold">
              <a class="acumin-gray-color" href="/">liFEsTlye</a>
            </h3>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto align-items-center">
          <% if current_user %>
          <li class="nav-item">
            <a href="/" class="p-2 text-dark nav-link">
              Home
            </a>
          </li>
          <li class="nav-item">
            <%= link_to "Create Article", new_article_path, class: "p-2 bg-acumin-color text-white rounded nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Create Category", new_category_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
              <i class="far fa-user-circle"></i>
            </a>
            <div class="dropdown-menu">
              <%= link_to "Logout", "/logout", class: "nav-link text-dark"%>
            </div>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_path, class: "nav-link text-dark" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", "/login", class: "nav-link text-dark" %>
          </li>
          <% end %>
        </ul>
      </nav>
      <!-- mobile nav -->
      <nav class="navbar navbar-expand-sm bg-white border-bottom fixed-top d-md-none">
        <ul class="navbar-nav flex-row align-items-center w-100 d-flex justify-content-between">
          <li class="nav-item">
            <i class="fas fa-bars hamburger acumin-gray-color"></i>
          </li>
          <li class="nav-item ml-3">
            <h3 class="acumin-gray-color font-weight-bold">
              <a class="acumin-gray-color" href="/">liFEsTlye</a>
            </h3>
          </li>
          <li class="nav-item">
            <a href="#">
              <i class="fas fa-search hamburger acumin-gray-color"></i>
            </a>
          </li>
        </ul>
      </nav>
    </header>
    <main id="page-container">
      <% if flash[:notice] %>
      <div class="row status">
        <div class="col-12">
          <div class="alert alert-success mr-auto ml-auto w-50 mt-3">
            <strong><%= notice %></strong>
          </div>
        </div>
      </div>
      <% end %>

      <div class="container-fluid content">
        <div class="row">
          <nav class="col-6 navbar bg-acumin-gray-color side-menu d-none">
            <ul class="navbar-nav text-white">
              <% if current_user %>
              <li class="nav-item">
                <%= link_to "Create Article", new_article_path, class: "nav-link text-uppercase" %>
              </li>

              <hr class="text-white border border-white w-100">

              <li class="nav-item">
                <a class="nav-link text-uppercase">
                  <i class="far fa-user-circle"></i>
                </a>
              </li>

              <li class="nav-item">
                <%= link_to "Logout", "/logout", class: "nav-link"%>
              </li>
              <% else %>
              <li class="nav-item">
                <%= link_to "Sign Up", new_user_path, class: "nav-link text-uppercase" %>
              </li>
              <li class="nav-item">
                <%= link_to "Sign In", "/login", class: "nav-link text-uppercase" %>
              </li>
              <% end %>
            </ul>
          </nav>
          <div id="overlay"></div>
        </div>

        <%= yield %>
      </div>

      <footer class="bg-acumin-gray-color container-fluid">
          <ul class="row">
            <li class="nav-item col-12 col-md-4">
              <h3 class="text-white font-weight-bold">
                <a class="text-white" href="/">liFEsTlye</a>
              </h3>
            </li>
            <li class="nav-item col-12 col-md-4">
              <a href="nav-item">
                Privacy Policy
              </a>
              <a href="nav-item">
                Terms & conditions
              </a>
              <p class="text-white">
                Copyright 2014. All rights reserved
              </p>
            </li>
            <li class="nav-item col-12 col-md-4">
              <div class="row d-flex justify-content-end">
                <div class="col-1">
                  <i class="fab fa-facebook acumin-color"></i>
                </div>
                <div class="col-1">
                  <i class="fab fa-twitter-square acumin-color"></i>
                </div>
                <div class="col-1">
                  <i class="fab fa-instagram-square acumin-color"></i>
                </div>
              </div>
            </li>
          </ul>
      </footer>
    </main>

    <%=javascript_include_tag "https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"  %>

    <script>
      $( document ).ready(function() {
        $('.hamburger').click(function() {
          console.log('dave');
          if ($(window).width() < 768) {
            $('.side-menu').toggleClass('d-none');
            $('#overlay').fadeToggle(300);
          }
        });
      });


      $(document).ready(function() {
          $('.js-example-basic-multiple').select2();
      });

    </script>
  </body>
</html>